
# Compiler settings
CC       = gcc
CFLAGS   = -Wall
LFLAGS   = -lm
OUT_NAME = ./ipc
SRC_MAIN = *.c

# Executable building rules
all: $(SRC_MAIN)
	$(CC) $(CFLAGS) -o $(OUT_NAME) $(SRC_MAIN) $(LFLAGS)
